const names =require('./names')
const sayHi =require('./utils')
const data =require('./alternative-flavor')
require('./mind-granade')
//console.log(data)
console.log(names)
sayHi('Suzzy')
sayHi(names.nam1)
sayHi(names.nam2)
sayHi(data.person)

